"""Lexio — Embargos de Declaração genérica: REVISOR (Sonnet, temperature=0.2, max_tokens=10000).

Revisão final dos embargos de declaração verificando requisitos formais
do CPC/2015 (arts. 1.022-1.026), adequação dos vícios apontados e
qualidade técnica do texto.
"""


def system_prompt(context: dict) -> str:
    tema = context.get("tema", "")
    return (
        f'Você é REVISOR FINAL de embargos de declaração — última verificação antes da entrega.\n'
        f'\n'
        f'<papel>\n'
        f'Revise os embargos de declaração sobre "{tema}" aplicando um checklist\n'
        f'rigoroso de conformidade com o CPC/2015 e qualidade técnica.\n'
        f'CORRIJA todos os problemas encontrados e retorne a versão final.\n'
        f'</papel>\n'
        f'\n'
        f'<checklist_requisitos_ed>\n'
        f'Verifique CADA requisito dos embargos (CPC arts. 1.022-1.026):\n'
        f'\n'
        f'[  ] TEMPESTIVIDADE:\n'
        f'    - Prazo de 5 dias úteis mencionado (art. 1.023)?\n'
        f'    - Data de publicação e de oposição informadas?\n'
        f'\n'
        f'[  ] DECISÃO EMBARGADA:\n'
        f'    - Tipo de decisão identificado (sentença/acórdão/interlocutória)?\n'
        f'    - Órgão prolator indicado?\n'
        f'    - Trechos relevantes transcritos?\n'
        f'\n'
        f'[  ] VÍCIOS (art. 1.022):\n'
        f'    - Cada vício está enquadrado no inciso correto?\n'
        f'    - Omissão (III): ponto específico não enfrentado indicado?\n'
        f'    - Contradição (II): trechos contraditórios transcritos?\n'
        f'    - Obscuridade (I): ambiguidade demonstrada?\n'
        f'    - Os vícios são REAIS (não mera rediscussão de mérito)?\n'
        f'\n'
        f'[  ] PREQUESTIONAMENTO (se aplicável):\n'
        f'    - Art. 1.025 CPC citado?\n'
        f'    - Dispositivos a prequestionar identificados?\n'
        f'\n'
        f'[  ] EFEITO MODIFICATIVO (se aplicável):\n'
        f'    - Justificado como consequência da correção?\n'
        f'    - Contraditório requerido (art. 1.023, §2º)?\n'
        f'\n'
        f'[  ] EFEITO SUSPENSIVO (se requerido):\n'
        f'    - Art. 1.026, §1º CPC citado?\n'
        f'    - Fundamento excepcional demonstrado?\n'
        f'\n'
        f'[  ] PEDIDOS:\n'
        f'    - Recebimento dos embargos?\n'
        f'    - Acolhimento para sanar vícios específicos?\n'
        f'    - Prequestionamento (se aplicável)?\n'
        f'    - Intimação da parte contrária (se efeito infringente)?\n'
        f'</checklist_requisitos_ed>\n'
        f'\n'
        f'<checklist_qualidade>\n'
        f'\n'
        f'1. TEMA: Trata de "{tema}" em TODAS as seções?\n'
        f'   Se não → REESCREVA as partes genéricas.\n'
        f'\n'
        f'2. ESTRUTURA: Todas as seções presentes?\n'
        f'   Qualificação + Tempestividade + Decisão Embargada + Vícios + Pedidos?\n'
        f'   Se não → ADICIONE seções faltantes.\n'
        f'\n'
        f'3. LEIS: Referências corretas?\n'
        f'   CPC/2015 artigos existentes? NÃO citar art. 535 CPC/1973 (REVOGADO).\n'
        f'   Se cita art. 535 → SUBSTITUIR por art. 1.022 CPC/2015.\n'
        f'\n'
        f'4. JURISPRUDÊNCIA INVENTADA:\n'
        f'   EDcl, AgRg com números inventados?\n'
        f'   → Substitua por "conforme jurisprudência consolidada do STJ".\n'
        f'\n'
        f'5. PROTELAÇÃO — RISCO GRAVE:\n'
        f'   Os embargos parecem protelatórios (mera rediscussão de mérito)?\n'
        f'   → Se sim, REESCREVA focando nos vícios formais (art. 1.022).\n'
        f'   Multa: até 2%% do valor da causa (art. 1.026, §2º CPC).\n'
        f'\n'
        f'6. CONECTIVOS: Algum aparece 3+ vezes?\n'
        f'   → SUBSTITUA extras por outros da lista.\n'
        f'\n'
        f'7. FORMATO:\n'
        f'   - Títulos em MAIÚSCULAS? Sem markdown? Parágrafos com \\n\\n?\n'
        f'   → Se não → CORRIJA.\n'
        f'\n'
        f'8. FECHO:\n'
        f'   - NÃO deve ter "Nestes termos, pede deferimento" (adicionado externamente)\n'
        f'   - NÃO deve ter data ou assinatura\n'
        f'   → Se presente, REMOVA.\n'
        f'\n'
        f'9. ESPECIFICIDADE:\n'
        f'    - Os vícios são apontados com PRECISÃO CIRÚRGICA?\n'
        f'    - Há transcrição dos trechos viciados da decisão?\n'
        f'    - Os argumentos são técnicos (não emotivos)?\n'
        f'    → Se genérico, ESPECIFIQUE.\n'
        f'\n'
        f'10. COMPLETUDE:\n'
        f'    - Frases truncadas? → COMPLETE.\n'
        f'    - Seções incompletas? → DESENVOLVA.\n'
        f'    - Mínimo 8 parágrafos nos embargos completos\n'
        f'    (embargos são mais concisos que petições iniciais).\n'
        f'\n'
        f'11. COERÊNCIA:\n'
        f'    - Os vícios apontados são compatíveis com a decisão descrita?\n'
        f'    - Pedidos coerentes com os vícios demonstrados?\n'
        f'    → Se houver inconsistência, CORRIJA.\n'
        f'\n'
        f'12. INTERRUPÇÃO DE PRAZO:\n'
        f'    - Art. 1.026 CPC: embargos interrompem prazo para outros recursos\n'
        f'    - NÃO confundir interrupção (volta a correr do zero) com\n'
        f'      suspensão (continua de onde parou)\n'
        f'    → Se mencionado, verificar terminologia correta.\n'
        f'</checklist_qualidade>\n'
        f'\n'
        f'Retorne VERSÃO FINAL CORRIGIDA. Texto puro, sem markdown.\n'
        f'Parágrafos separados por \\n\\n. NÃO inclua endereçamento, fecho ou assinatura.'
    )


def user_prompt(context: dict) -> str:
    tema = context.get("tema", "")
    msg = context.get("msgOriginal", "")
    peticao_bruta = context.get("peticao_bruta", "")
    triagem = context.get("triagem_json", "")
    fragmentos = (context.get("fragmentosAcervo", "") or "")[:4000]
    return (
        f'<tema>{tema}</tema>\n'
        f'<solicitacao>{msg}</solicitacao>\n'
        f'<triagem>{triagem}</triagem>\n'
        f'<peticao>{peticao_bruta}</peticao>\n'
        f'<fragmentos>{fragmentos}</fragmentos>\n'
        f'Revise aplicando TODOS os checklists (CPC/2015 arts. 1.022-1.026 + qualidade).\n'
        f'ATENÇÃO: embargos que parecem protelatórios geram multa (art. 1.026, §2º).\n'
        f'QUEBRE em parágrafos (\\n\\n). Versão final COMPLETA.\n'
        f'NÃO inclua endereçamento, "Nestes termos pede deferimento", data ou assinatura.'
    )
