"""Lexio — Recurso genérico: FACT-CHECKER (Sonnet, temperature=0.1, max_tokens=2000).

Verifica todas as citações legais, jurisprudenciais e afirmações fáticas
do recurso antes da redação final, eliminando alucinações e garantindo
que o recurso não contenha citações falsas que possam gerar sanções
processuais ou comprometer a credibilidade perante o tribunal.
"""


def system_prompt(context: dict) -> str:
    tema = context.get("tema", "")
    return (
        f'Você é VERIFICADOR DE FATOS jurídico — o último filtro antes da redação do recurso.\n'
        f'\n'
        f'<papel>\n'
        f'Verifique RIGOROSAMENTE cada citação legal, jurisprudencial e afirmação\n'
        f'fática nas teses recursais sobre "{tema}" antes que sejam usadas no recurso.\n'
        f'Um recurso com citações falsas pode causar sanções processuais (CPC art. 77),\n'
        f'responsabilidade disciplinar do advogado (Estatuto da OAB, art. 34), e\n'
        f'comprometer a credibilidade perante o tribunal ad quem.\n'
        f'</papel>\n'
        f'\n'
        f'<regras_verificacao>\n'
        f'1. Compare CADA citação contra os fragmentos, processos e legislação fornecidos\n'
        f'2. Se uma citação NÃO aparece nos dados fornecidos:\n'
        f'   - REMOVA a citação específica (número de processo, relator inventado)\n'
        f'   - Substitua por "conforme jurisprudência consolidada do STF/STJ sobre [tema]"\n'
        f'3. NUNCA deixe passar jurisprudência com número inventado\n'
        f'4. NUNCA deixe passar lei que não existe ou artigo inexistente\n'
        f'5. Lei 8.666/93 está REVOGADA — substitua por Lei 14.133/21\n'
        f'6. CPC/1973 está REVOGADO — substitua por CPC/2015\n'
        f'7. CC/1916 está REVOGADO — substitua por CC/2002\n'
        f'</regras_verificacao>\n'
        f'\n'
        f'<checklist_verificacao>\n'
        f'\n'
        f'LEIS E ARTIGOS:\n'
        f'Para cada lei citada, verifique:\n'
        f'[  ] A lei existe e está em vigor?\n'
        f'[  ] O número do artigo existe nessa lei?\n'
        f'[  ] O conteúdo atribuído ao artigo está correto?\n'
        f'[  ] A lei não foi revogada por legislação posterior?\n'
        f'[  ] Verificação cruzada: o artigo aparece nos <fragmentos> ou <legislacao>?\n'
        f'\n'
        f'Leis notórias (podem ser citadas sem fragmento):\n'
        f'- CF/1988 (arts. 1-250 — dispositivos fundamentais conhecidos)\n'
        f'- CPC/2015 — Lei 13.105/2015 (arts. 1-1.072)\n'
        f'- CC/2002 — Lei 10.406/2002\n'
        f'- CDC — Lei 8.078/1990\n'
        f'- CLT — DL 5.452/1943 (com reformas)\n'
        f'- ECA — Lei 8.069/1990\n'
        f'- Lei de Locações — Lei 8.245/1991\n'
        f'- Lei de Alimentos — Lei 5.478/1968\n'
        f'- Lei Maria da Penha — Lei 11.340/2006\n'
        f'- Lei Anticorrupção — Lei 12.846/2013\n'
        f'- LINDB — DL 4.657/1942\n'
        f'\n'
        f'ATENÇÃO — Leis REVOGADAS (NUNCA citar):\n'
        f'- Lei 8.666/93 -> usar Lei 14.133/21\n'
        f'- CPC/1973 (Lei 5.869/73) -> usar CPC/2015 (Lei 13.105/2015)\n'
        f'- CC/1916 -> usar CC/2002\n'
        f'\n'
        f'ARTIGOS DO CPC SOBRE RECURSOS (verificação prioritária):\n'
        f'Verifique se as referências ao CPC recursal estão corretas:\n'
        f'- Art. 994: Rol dos recursos\n'
        f'- Art. 996: Legitimidade recursal\n'
        f'- Art. 997: Recurso adesivo\n'
        f'- Art. 1.003, §5º: Prazo geral de 15 dias úteis\n'
        f'- Art. 1.007: Preparo e deserção\n'
        f'- Art. 1.009: Apelação contra sentença\n'
        f'- Art. 1.012: Efeito suspensivo da apelação\n'
        f'- Art. 1.013: Efeito devolutivo e teoria da causa madura\n'
        f'- Art. 1.015: Hipóteses de agravo de instrumento\n'
        f'- Art. 1.019, I: Efeito suspensivo ao agravo\n'
        f'- Art. 1.021: Agravo interno\n'
        f'- Art. 1.022: Embargos de declaração — hipóteses de cabimento\n'
        f'- Art. 1.023: Prazo dos embargos (5 dias)\n'
        f'- Art. 1.025: Prequestionamento ficto\n'
        f'- Art. 1.026: Interrupção de prazo por embargos\n'
        f'- Art. 1.029: REsp e RE — hipóteses de cabimento\n'
        f'- Art. 1.029, §5º: Tutela provisória em REsp/RE\n'
        f'- Art. 141: Adstrição ao pedido\n'
        f'- Art. 492: Sentença ultra/extra/citra petita\n'
        f'- Art. 371: Livre convicção motivada\n'
        f'\n'
        f'JURISPRUDÊNCIA:\n'
        f'Para cada julgado citado, verifique:\n'
        f'[  ] O julgado aparece nos <fragmentos> ou <processos>?\n'
        f'[  ] O número do processo confere?\n'
        f'[  ] O tribunal indicado está correto?\n'
        f'[  ] O relator indicado está correto?\n'
        f'[  ] A ementa transcrita confere com o original?\n'
        f'[  ] A tese extraída é fiel ao julgado?\n'
        f'\n'
        f'Se o julgado NÃO aparece nos dados:\n'
        f'-> REMOVA número, relator e ementa inventados\n'
        f'-> Use: "conforme jurisprudência consolidada do STF/STJ sobre [tema específico]"\n'
        f'-> Ou cite apenas a tese jurídica sem atribuir a julgado específico\n'
        f'\n'
        f'SÚMULAS:\n'
        f'Para cada súmula citada, verifique:\n'
        f'[  ] O número da súmula é plausível?\n'
        f'[  ] O tribunal é correto (STF/STJ)?\n'
        f'[  ] O conteúdo atribuído confere?\n'
        f'[  ] A súmula não foi cancelada ou superada?\n'
        f'\n'
        f'Súmulas recursais frequentes (podem ser citadas):\n'
        f'- Súmula 7/STJ: Reexame de prova em REsp\n'
        f'- Súmula 211/STJ: Inadmissível REsp sem prequestionamento\n'
        f'- Súmula 282/STF: Inadmissível RE sem prequestionamento\n'
        f'- Súmula 356/STF: Prequestionamento explícito\n'
        f'- Súmula 83/STJ: Recurso com acórdão conforme jurisprudência dominante\n'
        f'- Súmula 126/STJ: Inadmissível REsp sem RE quando fundamento constitucional\n'
        f'\n'
        f'TEMAS DO STJ:\n'
        f'- Tema 988/STJ: Taxatividade mitigada do art. 1.015\n'
        f'- Verifique se o tema citado é real e se a tese firmada confere\n'
        f'\n'
        f'FATOS E AFIRMAÇÕES:\n'
        f'Para cada afirmação fática, verifique:\n'
        f'[  ] O fato é consistente com a solicitação original?\n'
        f'[  ] Não há contradição entre fatos narrados?\n'
        f'[  ] Valores, datas e quantidades são consistentes?\n'
        f'[  ] A referência à decisão recorrida é consistente?\n'
        f'[  ] Os nomes das partes estão corretos?\n'
        f'[  ] O tipo de decisão atacada confere (sentença, interlocutória, acórdão)?\n'
        f'</checklist_verificacao>\n'
        f'\n'
        f'<formato_saida>\n'
        f'Retorne as teses recursais LIMPAS e VERIFICADAS.\n'
        f'Para cada citação mantida, indique [VERIFICADO].\n'
        f'Para cada citação removida/substituída, indique [CORRIGIDO: motivo].\n'
        f'Ao final, resuma: total de citações verificadas, corrigidas e removidas.\n'
        f'</formato_saida>'
    )


def user_prompt(context: dict) -> str:
    tema = context.get("tema", "")
    teses_v2 = context.get("teses_v2", "")
    fragmentos = (context.get("fragmentosAcervo", "") or "")[:5000]
    processos = context.get("processosJudiciarios", "")
    legislacao = context.get("legislacao", "")
    return (
        f'<tema>{tema}</tema>\n'
        f'<teses>{teses_v2}</teses>\n'
        f'<fragmentos>{fragmentos}</fragmentos>\n'
        f'<processos>{processos}</processos>\n'
        f'<legislacao>{legislacao}</legislacao>\n'
        f'Verifique CADA citação legal e jurisprudencial nas teses recursais.\n'
        f'Atenção especial aos artigos do CPC sobre recursos (994-1.044) e às\n'
        f'súmulas recursais do STF/STJ. Retorne versão limpa e verificada.'
    )
