import type { AgentModelDef } from '../../model-config'

// ── Chat Orchestrator Agent Definitions ──────────────────────────────────────

/**
 * Chat Orchestrator pipeline — multi-agent conversational engine that powers
 * the `/chat` page. The orchestrator decomposes the user request, dispatches
 * specialists in parallel/sequence, summarises history when budget tightens,
 * runs a critic, and emits the final answer. Specialists are invoked through
 * the same scoped-model loading pipeline as every other Lexio pipeline.
 *
 * PR1 ships the agent registry, settings and config card. The runtime loop
 * itself lands in PR2.
 */
export const CHAT_ORCHESTRATOR_AGENT_DEFS: AgentModelDef[] = [
  {
    key: 'chat_orchestrator',
    label: 'Orquestrador',
    description: 'Decide a próxima ação, despacha tools, invoca o crítico e emite a resposta final',
    defaultModel: '',
    recommendedTier: 'premium',
    icon: 'compass',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Núcleo do chat: precisa decidir entre dezenas de tools com confiabilidade. Premium: Claude Sonnet, GPT-4.1, GPT-4o, Gemini 2.5 Pro. Modelos médios funcionam mas perdem precisão em tool-calling.',
  },
  {
    key: 'chat_planner',
    label: 'Planejador',
    description: 'Quebra o pedido inicial em subtarefas e define a ordem ideal de execução',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'list-checks',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Planejamento estruturado curto. Premium: Claude Sonnet, GPT-4.1. Baratos: DeepSeek V3, Gemini 2.5 Flash, Llama 4 Maverick. Grátis: DeepSeek R1:free, Llama 3.3 70B:free.',
  },
  {
    key: 'chat_clarifier',
    label: 'Esclarecedor',
    description: 'Decide se vale interromper o usuário com uma pergunta antes de gastar mais tokens',
    defaultModel: '',
    recommendedTier: 'fast',
    icon: 'help-circle',
    agentCategory: 'extraction',
    requiredCapability: 'text',
    bestModelNote: 'Decisão rápida e barata. Claude Haiku, GPT-4o Mini, GPT-4.1 Nano, Gemini 2.5 Flash Lite, Llama 3.3 70B. Grátis: Gemini 2.0 Flash:free, Mistral Small:free.',
  },
  {
    key: 'chat_legal_researcher',
    label: 'Pesquisador Jurídico',
    description: 'Conduz pesquisa em DataJud e na web e sintetiza descobertas relevantes para o caso',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'gavel',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Síntese de jurisprudência e doutrina. Premium: Claude Sonnet, GPT-4o, Gemini 2.5 Pro. Baratos: DeepSeek V3, Gemini 2.5 Flash, Qwen 2.5 72B.',
  },
  {
    key: 'chat_code_writer',
    label: 'Programador',
    description: 'Gera ou edita código quando o turno envolve gravar/alterar arquivos via sidecar',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'code-2',
    agentCategory: 'writing',
    requiredCapability: 'text',
    bestModelNote: 'Geração de código. Premium: Claude Sonnet, GPT-4.1, GPT-4o. Baratos: DeepSeek V3, Qwen3 30B, Llama 4 Maverick.',
  },
  {
    key: 'chat_fs_actor',
    label: 'Operador de Arquivos',
    description: 'Traduz pedidos determinísticos em chamadas de filesystem/shell expostas pelo sidecar',
    defaultModel: '',
    recommendedTier: 'fast',
    icon: 'folder-cog',
    agentCategory: 'extraction',
    requiredCapability: 'text',
    bestModelNote: 'Mapeia ações em chamadas estruturadas. Modelos rápidos com boa aderência a JSON: GPT-4o Mini, Claude Haiku, Gemini 2.5 Flash, Mistral Small.',
  },
  {
    key: 'chat_summarizer',
    label: 'Sumarizador',
    description: 'Comprime o histórico da conversa quando o orçamento de tokens fica apertado',
    defaultModel: '',
    recommendedTier: 'fast',
    icon: 'file-minus',
    agentCategory: 'synthesis',
    requiredCapability: 'text',
    bestModelNote: 'Compressão semântica rápida. GPT-4o Mini, Claude Haiku, Gemini 2.5 Flash, Mistral Small. Grátis: Llama 3.3 70B:free, Qwen3 30B:free.',
  },
  {
    key: 'chat_critic',
    label: 'Crítico',
    description: 'Pontua o rascunho atual e decide se o orquestrador deve parar ou iterar mais',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'scale',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Avaliação crítica de qualidade. Premium: Claude Sonnet, GPT-4o. Baratos: DeepSeek V3, Gemini 2.5 Flash, Qwen 2.5 72B.',
  },
  {
    key: 'chat_writer',
    label: 'Redator',
    description: 'Produz a resposta final do turno em markdown rico, com citações e formatação',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'pen-line',
    agentCategory: 'writing',
    requiredCapability: 'text',
    bestModelNote: 'Redação final. Premium: Claude Sonnet, GPT-4.1, GPT-4o. Baratos: DeepSeek V3, Llama 4 Maverick, Gemini 2.5 Flash, Qwen 2.5 72B.',
  },
  {
    key: 'chat_argument_builder',
    label: 'Fundamentador',
    description: 'Constrói argumentação jurídica em quatro etapas: tese, sustentação com evidência, contra-argumento mais forte e refutação',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'milestone',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Raciocínio adversarial. Premium: Claude Sonnet, GPT-4.1. Baratos: DeepSeek V3, Gemini 2.5 Flash, Qwen 2.5 72B.',
  },
  {
    key: 'chat_ethics_auditor',
    label: 'Auditor Ético',
    description: 'Avalia a entrega em quatro lentes: representação, framing, impacto sobre grupos vulneráveis e conformidade (LGPD, OAB, normas aplicáveis)',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'shield-check',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Avaliação de conformidade e ética. Premium: Claude Sonnet, GPT-4o. Baratos: DeepSeek V3, Gemini 2.5 Flash.',
  },
  {
    key: 'chat_artifact_architect',
    label: 'Arquiteto de Artefatos',
    description: 'Classifica entregáveis do chat, define formato canônico, versionamento e manifesto JSON seguro',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'package-check',
    agentCategory: 'synthesis',
    requiredCapability: 'text',
    bestModelNote: 'Planejamento de entregáveis e schemas. Premium: Claude Sonnet, GPT-4.1. Baratos: Gemini Flash, DeepSeek V3, Qwen 2.5 72B.',
  },
  {
    key: 'chat_document_composer',
    label: 'Compositor de Documentos',
    description: 'Transforma pesquisa e decisões da trilha em documentos textuais estruturados, prontos para exportação',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'file-text',
    agentCategory: 'writing',
    requiredCapability: 'text',
    bestModelNote: 'Redação estruturada de documentos. Premium: Claude Sonnet, GPT-4.1, GPT-4o. Baratos: DeepSeek V3, Llama 4 Maverick, Gemini Flash.',
  },
  {
    key: 'chat_data_builder',
    label: 'Construtor de Dados',
    description: 'Cria tabelas, schemas, manifestos JSON e planilhas a partir dos resultados dos agentes',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'table-2',
    agentCategory: 'synthesis',
    requiredCapability: 'text',
    bestModelNote: 'Estruturação em JSON/tabelas. Premium: GPT-4.1, Claude Sonnet. Baratos: Gemini Flash, Qwen, DeepSeek V3.',
  },
  {
    key: 'chat_media_director',
    label: 'Diretor de Mídia',
    description: 'Planeja entregáveis multimodais e decide quando acionar pipelines de apresentação, áudio, vídeo ou imagem',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'clapperboard',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Roteamento multimodal e planejamento de produção. Premium: Claude Sonnet, Gemini Pro, GPT-4o. Baratos: Gemini Flash, DeepSeek V3.',
  },
  {
    key: 'chat_image_generator',
    label: 'Gerador de Imagem Literal',
    description: 'Gera imagens literais do chat e produz arquivos PNG/JPG/WEBP diretamente a partir do modelo configurado para essa função',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'image',
    agentCategory: 'synthesis',
    requiredCapability: 'image',
    bestModelNote: 'Use apenas modelos com geração nativa de imagem no catálogo pessoal, como Gemini Flash Image, GPT Image ou equivalentes suportados pelo provedor direto.',
  },
  {
    key: 'chat_multimodal_analysis',
    label: 'Analisador Multimodal',
    description: 'Lê imagens e frames de vídeos anexados, extrai OCR visual e resume evidências em contexto textual antes da trilha principal',
    defaultModel: 'openai/gpt-4o-mini',
    recommendedTier: 'balanced',
    icon: 'scan-eye',
    agentCategory: 'extraction',
    requiredCapability: 'image',
    bestModelNote: 'OCR e visão de anexos. Use modelos com entrada de imagem: GPT-4o Mini/GPT-4o, Claude Sonnet multimodal ou Gemini 2.5 Flash/Pro quando disponíveis no catálogo pessoal.',
  },
  {
    key: 'chat_image_evidence_specialist',
    label: 'Especialista em Imagens',
    description: 'Interpreta OCR, layout, metadados e sinais visuais extraídos de imagens anexadas para uso jurídico no turno',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'image',
    agentCategory: 'extraction',
    requiredCapability: 'text',
    bestModelNote: 'Trabalha sobre o texto/OCR extraído pelo analisador inicial. Priorize modelos bons em evidência visual, síntese jurídica e marcação de baixa confiança.',
  },
  {
    key: 'chat_audio_evidence_specialist',
    label: 'Especialista em Áudio',
    description: 'Analisa transcrições de áudio, identifica falas, lacunas, datas, valores e pontos juridicamente relevantes',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'mic',
    agentCategory: 'extraction',
    requiredCapability: 'text',
    bestModelNote: 'Roda após STT. Use modelos que distinguem transcrição literal de inferência e preservam dúvidas como [inaudível] ou [carece de verificação].',
  },
  {
    key: 'chat_video_evidence_specialist',
    label: 'Especialista em Vídeo',
    description: 'Cruza frames amostrados e transcrição de vídeo para resumir cenas, OCR, falas e limitações da prova audiovisual',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'video',
    agentCategory: 'extraction',
    requiredCapability: 'text',
    bestModelNote: 'Trabalha sobre frames/transcrição já convertidos em texto. Priorize modelos bons em cronologia, cautela probatória e separação entre observado e inferido.',
  },
  {
    key: 'chat_multimodal_evidence_synthesizer',
    label: 'Síntese Multimodal',
    description: 'Consolida evidências de imagens, áudios, vídeos e anexos textuais em uma matriz única de fatos, riscos e lacunas',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'scan-search',
    agentCategory: 'synthesis',
    requiredCapability: 'text',
    bestModelNote: 'Use quando houver mais de um anexo ou modalidades diferentes. Deve produzir matriz de evidências, pontos controvertidos e próximos passos verificáveis.',
  },
  {
    key: 'chat_audio_transcription',
    label: 'Transcritor de Áudio',
    description: 'Transcreve áudios anexados e faixas de áudio de vídeos pequenos antes da trilha principal',
    defaultModel: 'openai/gpt-4o-mini-transcribe',
    recommendedTier: 'fast',
    icon: 'mic',
    agentCategory: 'extraction',
    requiredCapability: 'audio',
    bestModelNote: 'STT para anexos de áudio/vídeo. Use GPT-4o Mini Transcribe para custo/latência equilibrados, GPT-4o Transcribe para maior qualidade ou Whisper quando precisar de compatibilidade ampla.',
  },
  {
    key: 'chat_export_packager',
    label: 'Empacotador de Exports',
    description: 'Valida formatos finais, nomes de arquivo, downloads e pacote de entrega exibido ao usuário',
    defaultModel: '',
    recommendedTier: 'fast',
    icon: 'download',
    agentCategory: 'extraction',
    requiredCapability: 'text',
    bestModelNote: 'Checagem objetiva de formatos e entrega. Modelos rápidos: GPT-4o Mini, Claude Haiku, Gemini Flash Lite, Mistral Small.',
  },
  {
    key: 'chat_audio_generator',
    label: 'Gerador de Áudio Literal',
    description: 'Sintetiza áudio literal (TTS) no chat e produz arquivos MP3/WAV prontos para preview e download a partir do modelo configurado para essa função',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'mic',
    agentCategory: 'synthesis',
    requiredCapability: 'audio',
    bestModelNote: 'Use apenas modelos com síntese de fala nativa no catálogo pessoal, como OpenAI TTS-1 / TTS-1-HD, Gemini TTS ou equivalentes suportados pelo provedor direto.',
  },
  {
    key: 'chat_presentation_designer',
    label: 'Designer de Apresentação',
    description: 'Gera os visuais literais dos slides de apresentações do chat, produzindo imagens de slide renderizadas para preview e export PPTX',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'image',
    agentCategory: 'synthesis',
    requiredCapability: 'image',
    bestModelNote: 'Use apenas modelos com geração nativa de imagem no catálogo pessoal, como Gemini Flash Image ou GPT Image. Os textos do deck usam os agentes textuais; este agente apenas renderiza os visuais dos slides.',
  },
  {
    key: 'chat_video_generator',
    label: 'Gerador de Vídeo Literal',
    description: 'Gera vídeo literal por IA para artefatos do chat, solicitando clipes reais a um provedor de vídeo (Veo, Kling, Wan, Sora, Runway e similares) e entregando o MP4 com player e download',
    defaultModel: '',
    recommendedTier: 'premium',
    icon: 'video',
    agentCategory: 'synthesis',
    requiredCapability: 'video',
    configurationMode: 'external-provider',
    configurationHint: 'Gerido por VITE_EXTERNAL_VIDEO_PROVIDER_*; aponte o endpoint para um agregador de vídeo real (ex.: fal.ai, Replicate, Veo) capaz de receber prompt e devolver URL final ou job_id/poll_url. O modelo de vídeo específico pode ser informado na chamada generate_video.',
    bestModelNote: 'Reservado para provedores de geração de vídeo real. Quando o provedor não estiver configurado, o chat finaliza com falha operacional acionável em vez de substituir por slideshow.',
  },
]
