import type { AgentModelDef } from '../../model-config'

// ── Chat Orchestrator Agent Definitions ──────────────────────────────────────

/**
 * Chat Orchestrator pipeline — multi-agent conversational engine that powers
 * the `/chat` page. The orchestrator decomposes the user request, dispatches
 * specialists in parallel/sequence, summarises history when budget tightens,
 * runs a critic, and emits the final answer. Specialists are invoked through
 * the same scoped-model loading pipeline as every other Lexio pipeline.
 *
 * PR1 ships the agent registry, settings and config card. The runtime loop
 * itself lands in PR2.
 */
export const CHAT_ORCHESTRATOR_AGENT_DEFS: AgentModelDef[] = [
  {
    key: 'chat_orchestrator',
    label: 'Orquestrador',
    description: 'Decide a próxima ação, despacha tools, invoca o crítico e emite a resposta final',
    defaultModel: '',
    recommendedTier: 'premium',
    icon: 'compass',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Núcleo do chat: precisa decidir entre dezenas de tools com confiabilidade. Premium: Claude Sonnet, GPT-4.1, GPT-4o, Gemini 2.5 Pro. Modelos médios funcionam mas perdem precisão em tool-calling.',
  },
  {
    key: 'chat_planner',
    label: 'Planejador',
    description: 'Quebra o pedido inicial em subtarefas e define a ordem ideal de execução',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'list-checks',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Planejamento estruturado curto. Premium: Claude Sonnet, GPT-4.1. Baratos: DeepSeek V3, Gemini 2.5 Flash, Llama 4 Maverick. Grátis: DeepSeek R1:free, Llama 3.3 70B:free.',
  },
  {
    key: 'chat_clarifier',
    label: 'Esclarecedor',
    description: 'Decide se vale interromper o usuário com uma pergunta antes de gastar mais tokens',
    defaultModel: '',
    recommendedTier: 'fast',
    icon: 'help-circle',
    agentCategory: 'extraction',
    requiredCapability: 'text',
    bestModelNote: 'Decisão rápida e barata. Claude Haiku, GPT-4o Mini, GPT-4.1 Nano, Gemini 2.5 Flash Lite, Llama 3.3 70B. Grátis: Gemini 2.0 Flash:free, Mistral Small:free.',
  },
  {
    key: 'chat_legal_researcher',
    label: 'Pesquisador Jurídico',
    description: 'Conduz pesquisa em DataJud e na web e sintetiza descobertas relevantes para o caso',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'gavel',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Síntese de jurisprudência e doutrina. Premium: Claude Sonnet, GPT-4o, Gemini 2.5 Pro. Baratos: DeepSeek V3, Gemini 2.5 Flash, Qwen 2.5 72B.',
  },
  {
    key: 'chat_code_writer',
    label: 'Programador',
    description: 'Gera ou edita código quando o turno envolve gravar/alterar arquivos via sidecar',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'code-2',
    agentCategory: 'writing',
    requiredCapability: 'text',
    bestModelNote: 'Geração de código. Premium: Claude Sonnet, GPT-4.1, GPT-4o. Baratos: DeepSeek V3, Qwen3 30B, Llama 4 Maverick.',
  },
  {
    key: 'chat_fs_actor',
    label: 'Operador de Arquivos',
    description: 'Traduz pedidos determinísticos em chamadas de filesystem/shell expostas pelo sidecar',
    defaultModel: '',
    recommendedTier: 'fast',
    icon: 'folder-cog',
    agentCategory: 'extraction',
    requiredCapability: 'text',
    bestModelNote: 'Mapeia ações em chamadas estruturadas. Modelos rápidos com boa aderência a JSON: GPT-4o Mini, Claude Haiku, Gemini 2.5 Flash, Mistral Small.',
  },
  {
    key: 'chat_summarizer',
    label: 'Sumarizador',
    description: 'Comprime o histórico da conversa quando o orçamento de tokens fica apertado',
    defaultModel: '',
    recommendedTier: 'fast',
    icon: 'file-minus',
    agentCategory: 'synthesis',
    requiredCapability: 'text',
    bestModelNote: 'Compressão semântica rápida. GPT-4o Mini, Claude Haiku, Gemini 2.5 Flash, Mistral Small. Grátis: Llama 3.3 70B:free, Qwen3 30B:free.',
  },
  {
    key: 'chat_critic',
    label: 'Crítico',
    description: 'Pontua o rascunho atual e decide se o orquestrador deve parar ou iterar mais',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'scale',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Avaliação crítica de qualidade. Premium: Claude Sonnet, GPT-4o. Baratos: DeepSeek V3, Gemini 2.5 Flash, Qwen 2.5 72B.',
  },
  {
    key: 'chat_writer',
    label: 'Redator',
    description: 'Produz a resposta final do turno em markdown rico, com citações e formatação',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'pen-line',
    agentCategory: 'writing',
    requiredCapability: 'text',
    bestModelNote: 'Redação final. Premium: Claude Sonnet, GPT-4.1, GPT-4o. Baratos: DeepSeek V3, Llama 4 Maverick, Gemini 2.5 Flash, Qwen 2.5 72B.',
  },
  {
    key: 'chat_argument_builder',
    label: 'Fundamentador',
    description: 'Constrói argumentação jurídica em quatro etapas: tese, sustentação com evidência, contra-argumento mais forte e refutação',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'milestone',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Raciocínio adversarial. Premium: Claude Sonnet, GPT-4.1. Baratos: DeepSeek V3, Gemini 2.5 Flash, Qwen 2.5 72B.',
  },
  {
    key: 'chat_ethics_auditor',
    label: 'Auditor Ético',
    description: 'Avalia a entrega em quatro lentes: representação, framing, impacto sobre grupos vulneráveis e conformidade (LGPD, OAB, normas aplicáveis)',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'shield-check',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Avaliação de conformidade e ética. Premium: Claude Sonnet, GPT-4o. Baratos: DeepSeek V3, Gemini 2.5 Flash.',
  },
  {
    key: 'chat_artifact_architect',
    label: 'Arquiteto de Artefatos',
    description: 'Classifica entregáveis do chat, define formato canônico, versionamento e manifesto JSON seguro',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'package-check',
    agentCategory: 'synthesis',
    requiredCapability: 'text',
    bestModelNote: 'Planejamento de entregáveis e schemas. Premium: Claude Sonnet, GPT-4.1. Baratos: Gemini Flash, DeepSeek V3, Qwen 2.5 72B.',
  },
  {
    key: 'chat_document_composer',
    label: 'Compositor de Documentos',
    description: 'Transforma pesquisa e decisões da trilha em documentos textuais estruturados, prontos para exportação',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'file-text',
    agentCategory: 'writing',
    requiredCapability: 'text',
    bestModelNote: 'Redação estruturada de documentos. Premium: Claude Sonnet, GPT-4.1, GPT-4o. Baratos: DeepSeek V3, Llama 4 Maverick, Gemini Flash.',
  },
  {
    key: 'chat_data_builder',
    label: 'Construtor de Dados',
    description: 'Cria tabelas, schemas, manifestos JSON e planilhas a partir dos resultados dos agentes',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'table-2',
    agentCategory: 'synthesis',
    requiredCapability: 'text',
    bestModelNote: 'Estruturação em JSON/tabelas. Premium: GPT-4.1, Claude Sonnet. Baratos: Gemini Flash, Qwen, DeepSeek V3.',
  },
  {
    key: 'chat_media_director',
    label: 'Diretor de Mídia',
    description: 'Planeja entregáveis multimodais e decide quando acionar pipelines de apresentação, áudio, vídeo ou imagem',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'clapperboard',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Roteamento multimodal e planejamento de produção. Premium: Claude Sonnet, Gemini Pro, GPT-4o. Baratos: Gemini Flash, DeepSeek V3.',
  },
  {
    key: 'chat_multimodal_analysis',
    label: 'Analisador Multimodal',
    description: 'Lê imagens anexadas, extrai OCR visual e resume evidências em contexto textual antes da trilha principal',
    defaultModel: 'openai/gpt-4o-mini',
    recommendedTier: 'balanced',
    icon: 'scan-eye',
    agentCategory: 'extraction',
    requiredCapability: 'image',
    bestModelNote: 'OCR e visão de anexos. Use modelos com entrada de imagem: GPT-4o Mini/GPT-4o, Claude Sonnet multimodal ou Gemini 2.5 Flash/Pro quando disponíveis no catálogo pessoal.',
  },
  {
    key: 'chat_export_packager',
    label: 'Empacotador de Exports',
    description: 'Valida formatos finais, nomes de arquivo, downloads e pacote de entrega exibido ao usuário',
    defaultModel: '',
    recommendedTier: 'fast',
    icon: 'download',
    agentCategory: 'extraction',
    requiredCapability: 'text',
    bestModelNote: 'Checagem objetiva de formatos e entrega. Modelos rápidos: GPT-4o Mini, Claude Haiku, Gemini Flash Lite, Mistral Small.',
  },
]
