export { PIPELINE_AGENT_DEFS } from './document-v2'
export { THESIS_ANALYST_AGENT_DEFS } from './thesis-analyst'
export { CONTEXT_DETAIL_AGENT_DEFS } from './context-detail'
export { ACERVO_CLASSIFICADOR_AGENT_DEFS } from './acervo-classificador'
export { ACERVO_EMENTA_AGENT_DEFS } from './acervo-ementa'
export { RESEARCH_NOTEBOOK_AGENT_DEFS } from './research-notebook'
export { NOTEBOOK_ACERVO_AGENT_DEFS } from './notebook-acervo'
export { VIDEO_PIPELINE_AGENT_DEFS, DEFAULT_VIDEO_TTS_VOICE } from './video'
export { AUDIO_PIPELINE_AGENT_DEFS } from './audio'
export { PRESENTATION_PIPELINE_AGENT_DEFS } from './presentation'
export { DOCUMENT_V3_PIPELINE_AGENT_DEFS } from './document-v3'
export { CHAT_ORCHESTRATOR_AGENT_DEFS } from './chat-orchestrator'
