import type { AgentModelDef } from '../../model-config'

// ── Presentation Generator v2 Agent Definitions ─────────────────────────────

/**
 * Multimodal presentation generator v2.
 *
 * This pipeline is intentionally separate from `PRESENTATION_PIPELINE_AGENT_DEFS`
 * so the legacy studio presentation flow can remain stable while v2 evolves.
 */
export const PRESENTATION_V2_PIPELINE_AGENT_DEFS: AgentModelDef[] = [
  {
    key: 'presentation_v2_orchestrator',
    label: 'Orquestrador v2',
    description: 'Avalia a solicitação inteira, decide perguntas de esclarecimento, escolhe agentes e controla o plano multimodal completo',
    defaultModel: '',
    recommendedTier: 'premium',
    icon: 'compass',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Núcleo decisório do v2. Prefira modelos premium com excelente planejamento, JSON confiável e compreensão multimodal indireta.',
  },
  {
    key: 'presentation_v2_context_auditor',
    label: 'Auditor de Contexto',
    description: 'Lê fontes, conversa e briefing para identificar lacunas, riscos, restrições e materiais úteis antes de planejar',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'scan-search',
    agentCategory: 'extraction',
    requiredCapability: 'text',
    bestModelNote: 'Precisa extrair sinais de fontes longas e apontar lacunas com baixo custo. Bons modelos fast/balanced com contexto amplo funcionam bem.',
  },
  {
    key: 'presentation_v2_clarifier',
    label: 'Clarificador',
    description: 'Formula perguntas objetivas de conteúdo, público, profundidade, formato e design quando o pedido ainda está ambíguo',
    defaultModel: '',
    recommendedTier: 'fast',
    icon: 'message-circle-question',
    agentCategory: 'extraction',
    requiredCapability: 'text',
    bestModelNote: 'Agente rápido para transformar lacunas em perguntas úteis no modal, sem gastar modelos premium.',
  },
  {
    key: 'presentation_v2_narrative_planner',
    label: 'Planejador Narrativo',
    description: 'Define começo, meio e fim, arco argumentativo, seções, ritmo e distribuição do número de slides decidido pelo usuário',
    defaultModel: '',
    recommendedTier: 'premium',
    icon: 'route',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Use modelo forte em raciocínio para montar estrutura progressiva, tese central e cadência da apresentação.',
  },
  {
    key: 'presentation_v2_researcher',
    label: 'Pesquisador',
    description: 'Seleciona evidências, exemplos, citações, dados e alertas a partir das fontes do caderno e do contexto da conversa',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'search',
    agentCategory: 'extraction',
    requiredCapability: 'text',
    bestModelNote: 'Modelo com bom contexto e precisão de extração para preservar evidência e evitar invenções.',
  },
  {
    key: 'presentation_v2_content_architect',
    label: 'Arquiteto de Conteúdo',
    description: 'Transforma pesquisa e plano narrativo em mapa slide a slide com objetivo, tese, prova, transição e carga cognitiva',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'layout-template',
    agentCategory: 'synthesis',
    requiredCapability: 'text',
    bestModelNote: 'Precisa gerar JSON estrutural consistente e reduzir excesso de informação por slide.',
  },
  {
    key: 'presentation_v2_slide_writer',
    label: 'Redator de Slides',
    description: 'Escreve títulos, bullets, notas do apresentador, microcopy visual e transições entre slides',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'file-text',
    agentCategory: 'writing',
    requiredCapability: 'text',
    bestModelNote: 'Priorize escrita clara em português brasileiro, síntese visual e notas completas do apresentador.',
  },
  {
    key: 'presentation_v2_visual_director',
    label: 'Diretor Visual',
    description: 'Define tema, grid, paleta, tipografia, layouts, fundos, hierarquia e direção visual por slide',
    defaultModel: '',
    recommendedTier: 'premium',
    icon: 'palette',
    agentCategory: 'synthesis',
    requiredCapability: 'text',
    bestModelNote: 'Modelo forte em estruturação visual para criar um sistema de design coeso e exportável.',
  },
  {
    key: 'presentation_v2_data_diagrammer',
    label: 'Dados e Diagramas',
    description: 'Planeja gráficos, tabelas, mapas conceituais, diagramas e visualizações quando o conteúdo exige representação visual',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'chart-no-axes-combined',
    agentCategory: 'synthesis',
    requiredCapability: 'text',
    bestModelNote: 'Use modelo confiável em JSON e raciocínio quantitativo para gerar especificações de gráficos e diagramas.',
  },
  {
    key: 'presentation_v2_asset_planner',
    label: 'Planejador de Assets',
    description: 'Decide quais slides precisam de imagem, áudio, vídeo, fundo, gráfico, ícone ou renderização final, com prompts e dependências',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'boxes',
    agentCategory: 'synthesis',
    requiredCapability: 'text',
    bestModelNote: 'Conecta design, roteiro e provedores multimodais sem gerar mídia desnecessária.',
  },
  {
    key: 'presentation_v2_image_generator',
    label: 'Gerador de Imagens',
    description: 'Gera imagens e fundos reais para os slides quando o plano multimodal pedir materialização visual',
    defaultModel: 'google/gemini-2.5-flash-image',
    recommendedTier: 'balanced',
    icon: 'image-plus',
    agentCategory: 'synthesis',
    requiredCapability: 'image',
    bestModelNote: 'Modelo de imagem real. Gemini Flash Image é o padrão operacional inicial; modelos premium podem ser usados para qualidade superior.',
  },
  {
    key: 'presentation_v2_audio_director',
    label: 'Diretor de Áudio',
    description: 'Planeja narração, ritmo, pausas, trilha, locução e assets TTS quando a apresentação pedir áudio',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'headphones',
    agentCategory: 'writing',
    requiredCapability: 'text',
    bestModelNote: 'Texto forte para roteiro de narração e direção sonora; TTS real fica no agente dedicado.',
  },
  {
    key: 'presentation_v2_tts',
    label: 'Narrador TTS',
    description: 'Converte narração aprovada em áudio real para o deck ou para slides específicos',
    defaultModel: 'openai/tts-1-hd',
    recommendedTier: 'premium',
    icon: 'mic',
    agentCategory: 'synthesis',
    requiredCapability: 'audio',
    bestModelNote: 'Modelo TTS real. Use voz profissional e consistente com o público da apresentação.',
  },
  {
    key: 'presentation_v2_video_director',
    label: 'Diretor de Vídeo',
    description: 'Planeja clipes, cenas, movimento, b-roll e transições quando o deck exigir vídeo ou motion assets',
    defaultModel: '',
    recommendedTier: 'premium',
    icon: 'video',
    agentCategory: 'synthesis',
    requiredCapability: 'text',
    bestModelNote: 'Planejamento técnico de vídeo e prompts de clipes; a execução real depende do provedor externo configurado.',
  },
  {
    key: 'presentation_v2_video_generator',
    label: 'Gerador de Clipes',
    description: 'Solicita clipes a provedores externos de vídeo quando habilitados e registra fallback quando indisponíveis',
    defaultModel: '',
    recommendedTier: 'premium',
    icon: 'film',
    agentCategory: 'synthesis',
    requiredCapability: 'video',
    configurationMode: 'external-provider',
    configurationHint: 'Gerido por VITE_EXTERNAL_VIDEO_PROVIDER_*; requer endpoint HTTP capaz de receber prompt e devolver URL final ou job_id/poll_url.',
    bestModelNote: 'Reservado para provedores de vídeo reais. Se não houver provedor compatível, o pipeline deve degradar para plano de vídeo sem falhar o deck.',
  },
  {
    key: 'presentation_v2_reviewer',
    label: 'Revisor Multimodal',
    description: 'Audita narrativa, precisão jurídica, legibilidade, acessibilidade, coesão visual, riscos e completude multimodal',
    defaultModel: '',
    recommendedTier: 'balanced',
    icon: 'shield-check',
    agentCategory: 'reasoning',
    requiredCapability: 'text',
    bestModelNote: 'Modelo crítico com boa aderência a rubricas de qualidade, acessibilidade e precisão jurídica.',
  },
  {
    key: 'presentation_v2_packager',
    label: 'Empacotador',
    description: 'Normaliza o JSON final, prepara hints de exportação, status de assets e histórico de revisão para viewer/PPTX',
    defaultModel: '',
    recommendedTier: 'fast',
    icon: 'package-check',
    agentCategory: 'synthesis',
    requiredCapability: 'text',
    bestModelNote: 'Agente de acabamento estrutural; deve ser barato, confiável em JSON e pouco criativo.',
  },
]