/**
 * Default Markdown structures for each of the 10 built-in document types.
 * Extracted from firestore-service.ts for modularity.
 */
export const DEFAULT_DOC_STRUCTURES: Record<string, string> = {
  parecer: [
    '# PARECER JURÍDICO',
    '',
    '## RELATÓRIO',
    '- Descrição do tema com contexto fático (2-3 parágrafos)',
    '- Delimitação do escopo da análise',
    '',
    '## FUNDAMENTAÇÃO JURÍDICA',
    '- Subseções com TÍTULOS DESCRITIVOS EM MAIÚSCULAS',
    '- Cada subseção: tese + artigo transcrito + jurisprudência + aplicação ao caso',
    '- Mínimo 8 parágrafos longos (4+ linhas)',
    '- Camadas: CF > Legislação Federal > Legislação Estadual > Jurisprudência > Caso concreto',
    '',
    '### DA FUNDAMENTAÇÃO CONSTITUCIONAL',
    '- Princípios e direitos fundamentais aplicáveis',
    '- Artigos da CF/88 transcritos',
    '',
    '### DA FUNDAMENTAÇÃO LEGAL',
    '- Legislação infraconstitucional pertinente',
    '- Artigos transcritos entre aspas',
    '',
    '### DA FUNDAMENTAÇÃO JURISPRUDENCIAL',
    '- Súmulas com enunciado completo',
    '- Temas de repercussão geral/repetitivos',
    '',
    '### DA FUNDAMENTAÇÃO DOUTRINÁRIA',
    '- Autores de referência com obra e posição',
    '',
    '## CONCLUSÃO',
    '- Síntese da análise',
    '- Recomendação concreta',
    '- "É o parecer, salvo melhor juízo."',
  ].join('\n'),

  peticao_inicial: [
    '# PETIÇÃO INICIAL',
    '> Estrutura conforme CPC/2015, arts. 319-320',
    '',
    '## I. QUALIFICAÇÃO DAS PARTES (CPC art. 319, II)',
    '- Nome, nacionalidade, estado civil, profissão',
    '- RG e CPF (ou CNPJ para pessoa jurídica)',
    '- Endereço completo',
    '- Qualificação do réu',
    '',
    '## II. DOS FATOS (CPC art. 319, III — causa de pedir remota)',
    '- Narração clara, cronológica e detalhada dos fatos',
    '- Mínimo 4-6 parágrafos longos (5+ linhas cada)',
    '- Descreva: o que aconteceu, quando, como, consequências',
    '- Mencione tentativas de solução extrajudicial (se houver)',
    '- Referência a documentos probatórios',
    '',
    '## III. DO DIREITO (CPC art. 319, III — causa de pedir próxima)',
    '- Subseções com títulos descritivos em maiúsculas',
    '- Cada subseção desenvolve uma tese:',
    '  - (a) Enunciado da tese',
    '  - (b) Fundamento constitucional (se aplicável)',
    '  - (c) Fundamento legal — transcreva artigos relevantes entre aspas',
    '  - (d) Jurisprudência — transcreva ementas relevantes',
    '  - (e) Aplicação ao caso concreto — subsunção fato-norma',
    '- Mínimo 3 subseções com 3+ parágrafos longos cada',
    '- Camadas: CF > Legislação Federal > Legislação Especial > Jurisprudência > Caso',
    '',
    '## IV. DA TUTELA PROVISÓRIA (se aplicável)',
    '### Urgência (CPC art. 300):',
    '- Probabilidade do direito (fumus boni iuris)',
    '- Perigo de dano irreparável (periculum in mora)',
    '### Evidência (CPC art. 311):',
    '- Enquadre no inciso aplicável (I a IV)',
    '',
    '## V. DOS PEDIDOS (CPC art. 319, IV)',
    '- a) Tutela provisória (se aplicável)',
    '- b) Citação do réu para contestar no prazo legal (CPC art. 335)',
    '- c) Audiência de conciliação/mediação (CPC art. 334) ou sua dispensa',
    '- d) Pedido principal — claro e específico',
    '- e) Pedidos acessórios: juros de mora, correção monetária',
    '- f) Condenação do réu em custas processuais e honorários advocatícios',
    '- g) Pedido subsidiário (se houver)',
    '- h) Produção de todas as provas em direito admitidas',
    '- i) Concessão dos benefícios da justiça gratuita (se aplicável)',
    '',
    '## VI. DO VALOR DA CAUSA (CPC art. 291-293)',
    '- Valor em reais e por extenso',
    '',
    '## VII. DAS PROVAS (CPC art. 319, VI)',
    '- Prova documental, testemunhal, pericial, depoimento pessoal do réu',
  ].join('\n'),

  contestacao: [
    '# CONTESTAÇÃO',
    '> Estrutura conforme CPC/2015, arts. 335-342',
    '',
    '## DA SÍNTESE DA INICIAL',
    '- Resumo dos fatos narrados pelo autor (2-3 parágrafos)',
    '- Identificação dos pedidos formulados',
    '- Identificação da causa de pedir',
    '',
    '## DAS PRELIMINARES (art. 337 CPC)',
    '- Somente se houver preliminares sólidas',
    '- Para cada preliminar:',
    '  - Título em MAIÚSCULAS',
    '  - Enquadramento legal: "Nos termos do art. 337, inciso [X]..."',
    '  - Fatos que sustentam a preliminar',
    '  - Fundamentação jurídica (legislação + jurisprudência)',
    '  - Consequência processual',
    '  - Pedido específico',
    '',
    '## DAS PREJUDICIAIS DE MÉRITO (se aplicável)',
    '- Prescrição ou decadência',
    '- Demonstrar o transcurso do prazo com datas precisas',
    '- Fundamentar: artigo do CC/CDC + jurisprudência',
    '',
    '## DO MÉRITO',
    '- Subseções com TÍTULOS DESCRITIVOS EM MAIÚSCULAS',
    '- Impugnação ESPECÍFICA de cada fato (art. 341 CPC):',
    '  1. Identifique o fato alegado pelo autor',
    '  2. Impugne especificamente: negue, contextualize ou justifique',
    '  3. Apresente a versão do réu',
    '  4. Fundamente com legislação (transcreva artigos entre aspas)',
    '  5. Cite jurisprudência de apoio',
    '  6. Conclua aplicando ao caso concreto',
    '- Camadas de fundamentação:',
    '  - Fundamento constitucional (CF)',
    '  - Fundamento legal (legislação infraconstitucional)',
    '  - Fundamento jurisprudencial',
    '  - Aplicação ao caso concreto (subsunção)',
    '- Ônus da prova (art. 373 CPC)',
    '- Mínimo 10 parágrafos longos (5+ linhas) no mérito',
    '',
    '## DAS PROVAS',
    '- Provas que o réu pretende produzir',
    '- Impugnação de provas do autor',
    '',
    '## DA RECONVENÇÃO (art. 343 CPC) — se cabível',
    '- Fundamento: art. 343 CPC + conexão com a ação principal',
    '- Fatos e fundamento jurídico da pretensão reconvencional',
    '- Pedido reconvencional específico',
    '',
    '## DOS PEDIDOS',
    '1. Preliminarmente (se houver): acolhimento da preliminar',
    '2. Prejudicial (se houver): reconhecimento da prescrição/decadência',
    '3. No mérito: julgamento de TOTAL IMPROCEDÊNCIA',
    '4. Subsidiário (se aplicável): redução de valor/obrigação',
    '5. Condenação do autor ao pagamento de custas e honorários',
    '6. Litigância de má-fé (se fundamentada)',
    '7. Produção de todas as provas em direito admitidas',
  ].join('\n'),

  recurso: [
    '# RECURSO',
    '> Estrutura adaptável a Apelação, Agravo, Embargos, REsp e RE',
    '',
    '## I. IDENTIFICAÇÃO E QUALIFICAÇÃO',
    '- Nome do recorrente, já qualificado nos autos',
    '- Tipo do recurso (Apelação / Agravo / Embargos de Declaração / REsp / RE)',
    '- Fundamento legal (artigo do CPC)',
    '',
    '## II. DA TEMPESTIVIDADE',
    '- Data da intimação e data da interposição',
    '- Prazo aplicável (art. 1.003, §5º, CPC: 15 dias úteis)',
    '',
    '## III. DO CABIMENTO',
    '- Demonstrar o cabimento do recurso interposto',
    '- Apelação: sentença que extinguiu ou julgou o mérito (art. 1.009)',
    '- Agravo de Instrumento: decisão interlocutória (art. 1.015)',
    '- Embargos: obscuridade, contradição ou omissão (art. 1.022)',
    '- Legitimidade e interesse recursal',
    '- Preparo ou hipótese de dispensa',
    '',
    '## IV. DOS FATOS',
    '- Narração clara e concisa dos fatos relevantes',
    '- Síntese do que foi pleiteado na instância de origem',
    '- Descrição objetiva da decisão recorrida',
    '- Identificação dos pontos de irresignação',
    '- Mínimo 3-4 parágrafos longos (5+ linhas cada)',
    '',
    '## V. DAS RAZÕES DO RECURSO (SEÇÃO PRINCIPAL)',
    '- Subseções com TÍTULOS DESCRITIVOS EM MAIÚSCULAS',
    '- Cada subseção desenvolve uma tese:',
    '  - (a) Identificação do erro da decisão recorrida (in judicando ou in procedendo)',
    '  - (b) O que a decisão fez de errado (transcrever trecho se possível)',
    '  - (c) Fundamento legal correto — artigos transcritos entre aspas',
    '  - (d) Jurisprudência que sustenta a reforma',
    '  - (e) Aplicação ao caso — por que a decisão merece reforma',
    '- Mínimo 3 subseções com 3+ parágrafos longos cada',
    '',
    '### Para Apelação:',
    '- Error in judicando (má aplicação do direito)',
    '- Error in procedendo (vício processual)',
    '- Efeito devolutivo amplo (art. 1.013)',
    '',
    '### Para Agravo de Instrumento:',
    '- Enquadramento no art. 1.015',
    '- Efeito suspensivo (se requerido)',
    '',
    '## VI. DO EFEITO SUSPENSIVO (se aplicável)',
    '- Probabilidade de provimento do recurso',
    '- Risco de dano irreparável ou de difícil reparação',
    '',
    '## VII. DO PREQUESTIONAMENTO (se aplicável — para REsp/RE)',
    '- Prequestionar expressamente os dispositivos legais debatidos',
    '',
    '## VIII. DOS PEDIDOS',
    '- a) Recebimento e regular processamento do recurso',
    '- b) Efeito suspensivo (se aplicável)',
    '- c) Intimação do recorrido para contrarrazões',
    '- d) PROVIMENTO do recurso para REFORMAR a decisão',
    '- e) Subsidiariamente, ANULAÇÃO da decisão',
    '- f) Inversão dos ônus sucumbenciais',
    '- g) Prequestionamento dos dispositivos legais (se aplicável)',
  ].join('\n'),

  sentenca: [
    '# SENTENÇA',
    '> Estrutura conforme CPC/2015, art. 489',
    '',
    '## RELATÓRIO (CPC art. 489, I)',
    '- Identificação das PARTES (autor/réu)',
    '- Descrição da PRETENSÃO do autor (síntese do pedido)',
    '- Resumo da CONTESTAÇÃO do réu (síntese da defesa)',
    '- Principais ocorrências processuais:',
    '  - Citação, contestação, réplica',
    '  - Audiências realizadas',
    '  - Provas produzidas (documental, testemunhal, pericial)',
    '  - Manifestações finais',
    '- Encerrar com: "É o relatório. Decido." ou "É o breve relatório. Fundamento e decido."',
    '',
    '## FUNDAMENTAÇÃO (CPC art. 489, II e §1º) — SEÇÃO PRINCIPAL',
    '- Subseções com TÍTULOS DESCRITIVOS EM MAIÚSCULAS',
    '- Se houver PRELIMINARES: enfrentar PRIMEIRO, individualmente',
    '- MÉRITO: analisar CADA pedido separadamente',
    '',
    '### Para cada questão:',
    '1. Identificar a TESE de cada parte',
    '2. Citar a NORMA aplicável com explicação da relação com o caso (art. 489, §1º, I)',
    '3. Se usar conceito indeterminado → explicar incidência concreta (art. 489, §1º, II)',
    '4. ENFRENTAR argumentos de AMBAS as partes (art. 489, §1º, IV)',
    '5. Precedentes com fundamentos determinantes (art. 489, §1º, V)',
    '6. Analisar PROVAS e ônus probatório (CPC art. 373)',
    '7. Subsunção ao caso concreto',
    '8. Conclusão parcial para cada pedido',
    '',
    '- Mínimo 10 parágrafos longos (4+ linhas)',
    '- Camadas: CF > Legislação > Jurisprudência > Caso concreto',
    '',
    '## DISPOSITIVO (CPC art. 489, III)',
    '- Comando decisório CLARO e DIRETO:',
    '  "Ante o exposto, JULGO [PROCEDENTE/IMPROCEDENTE/PARCIALMENTE PROCEDENTE]..."',
    '- Listar CADA providência concreta (condenar, declarar, constituir, determinar)',
    '- CUSTAS processuais: atribuição ao vencido (CPC art. 82, §2º)',
    '- HONORÁRIOS ADVOCATÍCIOS: fixar percentual ou valor (CPC art. 85)',
    '  - Regra: 10% a 20% sobre o valor da condenação',
    '  - Se improcedente: sobre o valor da causa',
    '- CORREÇÃO MONETÁRIA e JUROS DE MORA (quando aplicável):',
    '  - Índice de correção (IPCA-E, INPC, etc.)',
    '  - Juros: 1% a.m. ou SELIC conforme o caso',
    '  - Termo inicial de incidência',
    '- Se obrigação de fazer/não fazer:',
    '  - Prazo para cumprimento',
    '  - Multa cominatória (astreintes) se aplicável',
    '- Resolução do mérito: "com resolução do mérito, nos termos do art. 487, I, do CPC"',
  ].join('\n'),

  acao_civil_publica: [
    '# AÇÃO CIVIL PÚBLICA',
    '> Estrutura conforme Lei 7.347/85 (LACP)',
    '',
    '## DA LEGITIMIDADE ATIVA DO MINISTÉRIO PÚBLICO',
    '- CF art. 129, III: função institucional do MP',
    '- Lei 7.347/85 art. 5º, I: MP como legitimado ativo',
    '- CDC art. 82, I: legitimidade para tutela coletiva',
    '- Pertinência temática',
    '- Jurisprudência sobre a legitimidade',
    '',
    '## DA COMPETÊNCIA',
    '- Lei 7.347/85 art. 2º: foro do local do dano',
    '- Identificação da comarca competente',
    '- Se Justiça Federal: fundamentar (CF art. 109)',
    '',
    '## DO INQUÉRITO CIVIL',
    '- Referência ao IC, PP ou PA instaurado',
    '- Resumo das diligências realizadas',
    '- Provas colhidas',
    '- Conclusão do IC que fundamenta a ACP',
    '',
    '## DOS FATOS',
    '- Narrativa circunstanciada e cronológica (4-6 parágrafos longos)',
    '- Contexto factual detalhado',
    '- Conduta ilícita do requerido',
    '- Dano ao interesse transindividual',
    '- Nexo causal entre conduta e dano',
    '- Extensão e gravidade dos danos',
    '- Elementos probatórios (referência ao IC)',
    '',
    '## DO DIREITO',
    '- Subseções com TÍTULOS DESCRITIVOS EM MAIÚSCULAS',
    '- Fundamento constitucional (CF + direito material violado)',
    '- Lei 7.347/85: artigos aplicáveis com explicação',
    '- Legislação setorial: normas específicas do tema',
    '- Princípios aplicáveis ao caso',
    '- Jurisprudência consolidada',
    '- Subsunção ao caso concreto',
    '- Camadas: CF > LACP > Legislação setorial > Jurisprudência > Caso',
    '- Mínimo 6-10 parágrafos longos com citações',
    '',
    '## DO DANO MORAL COLETIVO (quando aplicável)',
    '- Conceito e fundamento legal',
    '- Demonstração da lesão extrapatrimonial coletiva',
    '- Parâmetros para quantificação',
    '- Jurisprudência do STJ',
    '- Destinação ao fundo (LACP art. 13)',
    '',
    '## DA TUTELA DE URGÊNCIA (quando aplicável)',
    '- LACP art. 12 + CPC arts. 300-302',
    '- Probabilidade do direito',
    '- Perigo de dano irreparável',
    '- Reversibilidade da medida',
    '',
    '## DOS PEDIDOS',
    '- a) Tutela de urgência (se aplicável): medida liminar concreta e específica',
    '- b) Citação do(s) requerido(s) para contestar',
    '- c) Procedência dos pedidos para:',
    '  - Obrigação de fazer (especificar)',
    '  - Obrigação de não fazer (especificar)',
    '  - Condenação em dinheiro (especificar valor)',
    '  - Dano moral coletivo (valor + fundo art. 13 LACP)',
    '- d) Fixação de multa diária (astreintes) por dia de descumprimento',
    '- e) Condenação do requerido ao pagamento de custas processuais',
    '- f) Produção de todas as provas admitidas em direito',
    '- Valor da causa',
  ].join('\n'),

  mandado_seguranca: [
    '# MANDADO DE SEGURANÇA',
    '> Estrutura conforme Lei 12.016/09 e CF art. 5º, LXIX',
    '',
    '## I. QUALIFICAÇÃO DO IMPETRANTE E AUTORIDADE COATORA',
    '- Nome e qualificação completa do impetrante',
    '- Indicação: MANDADO DE SEGURANÇA (COM PEDIDO DE LIMINAR, se aplicável)',
    '- Autoridade coatora: cargo, órgão e pessoa jurídica de direito público',
    '- Nota: indicar autoridade coatora E pessoa jurídica (art. 6º Lei 12.016/09)',
    '',
    '## II. DO ATO IMPUGNADO',
    '- Descrição clara e precisa do ato ilegal ou abusivo de poder',
    '- Data do ato ou ciência pelo impetrante (para contagem dos 120 dias)',
    '- Consequências concretas do ato para o impetrante',
    '- Mínimo 3-4 parágrafos longos',
    '',
    '## III. DO CABIMENTO DO MANDADO DE SEGURANÇA',
    '- Cabimento com base no art. 1º Lei 12.016/09 e CF art. 5º, LXIX',
    '- Afastar hipóteses de não cabimento (art. 5º Lei 12.016/09)',
    '- Observância do prazo de 120 dias (art. 23)',
    '- Competência do juízo',
    '',
    '## IV. DO DIREITO LÍQUIDO E CERTO',
    '- Subseções com TÍTULOS DESCRITIVOS EM MAIÚSCULAS',
    '- Cada subseção desenvolve uma tese',
    '- Demonstrar que o direito é líquido e certo (prova pré-constituída)',
    '- Fundamento constitucional + legal + jurisprudencial',
    '- Mínimo 3 subseções com 3+ parágrafos longos cada',
    '',
    '## V. DA ILEGALIDADE / DO ABUSO DE PODER',
    '- Demonstrar ilegalidade (contrariedade à norma) OU abuso de poder',
    '- Invocar princípios do art. 37 CF',
    '- Legislação específica violada pelo ato',
    '',
    '## VI. DA MEDIDA LIMINAR (se aplicável — art. 7º, III Lei 12.016/09)',
    '- Fundamento relevante (plausibilidade jurídica do pedido)',
    '- Perigo de ineficácia da medida se concedida ao final',
    '- Demonstrar que não há vedação legal à liminar',
    '',
    '## VII. DOS PEDIDOS',
    '- a) Concessão de medida liminar (se aplicável)',
    '- b) Notificação da autoridade coatora para prestar informações (art. 7º, I)',
    '- c) Ciência ao órgão de representação judicial da pessoa jurídica (art. 7º, II)',
    '- d) Oitiva do Ministério Público (art. 12)',
    '- e) Concessão da segurança em definitivo',
    '- f) Condenação da pessoa jurídica ao pagamento de custas (sem honorários — Súmula 105/STJ)',
  ].join('\n'),

  habeas_corpus: [
    '# HABEAS CORPUS',
    '> Estrutura conforme CPP arts. 647-660 e CF art. 5º, LXVIII',
    '',
    '## I. IDENTIFICAÇÃO DAS PARTES',
    '- Impetrante: nome e qualificação',
    '- Indicação: ORDEM DE HABEAS CORPUS (COM PEDIDO DE LIMINAR, se aplicável)',
    '- Paciente: nome, qualificação e situação atual (preso em...)',
    '- Autoridade coatora: cargo e órgão',
    '- Fundamento: art. 5º, LXVIII, da CF e arts. 647 e seguintes do CPP',
    '',
    '## II. DOS FATOS',
    '- Narração clara e cronológica dos fatos que levaram ao constrangimento',
    '- Descrição: prisão/restrição, quando ocorreu, circunstâncias',
    '- Processo de origem (se houver): número, fase, decisão impugnada',
    '- Consequências para o paciente',
    '- Mínimo 3-4 parágrafos longos',
    '',
    '## III. DO CONSTRANGIMENTO ILEGAL',
    '- Subseções com TÍTULOS DESCRITIVOS EM MAIÚSCULAS',
    '- Cada subseção desenvolve uma tese',
    '- Enquadrar no CPP art. 648 (inciso específico)',
    '- Fundamentação constitucional e legal',
    '- Jurisprudência de apoio',
    '- Mínimo 3 subseções com 3+ parágrafos longos cada',
    '',
    '### Argumentos obrigatórios conforme o tipo:',
    '- Prisão preventiva: ausência de requisitos do art. 312 CPP; medidas cautelares alternativas (art. 282/319 CPP)',
    '- Excesso de prazo: demonstrar a mora processual',
    '- Falta de justa causa: demonstrar fragilidade dos indícios',
    '- Presunção de inocência (CF art. 5º, LVII) como reforço',
    '- Liberdade como regra, prisão como exceção (CF art. 5º, LXVI)',
    '',
    '## IV. DO PEDIDO DE LIMINAR (se aplicável)',
    '- Fumus boni iuris: plausibilidade do constrangimento ilegal',
    '- Periculum in mora: dano irreparável à liberdade do paciente',
    '- Urgência: paciente preso ilegalmente ou sob ameaça concreta',
    '',
    '## V. DOS PEDIDOS',
    '- a) Concessão de liminar para expedição de alvará de soltura / salvo-conduto',
    '- b) Requisição de informações da autoridade coatora (CPP art. 662)',
    '- c) Oitiva do Ministério Público',
    '- d) Concessão da ordem em definitivo para cessar o constrangimento ilegal',
    '- Se HC liberatório: alvará de soltura imediato',
    '- Se HC preventivo: expedição de salvo-conduto',
  ].join('\n'),

  agravo: [
    '# AGRAVO DE INSTRUMENTO',
    '> Estrutura conforme CPC/2015, arts. 1.015-1.020',
    '',
    '## I. QUALIFICAÇÃO DAS PARTES (art. 1.016, I CPC)',
    '- Agravante: nome e qualificação',
    '- Referência aos autos da ação de origem',
    '- AGRAVO DE INSTRUMENTO (COM PEDIDO DE EFEITO SUSPENSIVO / TUTELA RECURSAL)',
    '- Contra a decisão interlocutória proferida pelo juízo de origem',
    '- Agravado: identificação',
    '',
    '## II. DA TEMPESTIVIDADE',
    '- Data da intimação da decisão',
    '- Data da interposição do recurso',
    '- Prazo de 15 dias úteis observado (art. 1.003, §5º CPC)',
    '',
    '## III. DO CABIMENTO (art. 1.015 CPC)',
    '- Identificar o inciso do art. 1.015 CPC aplicável',
    '- Se taxatividade mitigada: demonstrar urgência (Tema 988/STJ)',
    '- Fundamentar a adequação do agravo de instrumento',
    '',
    '## IV. DOS FATOS E DA DECISÃO AGRAVADA (art. 1.016, II CPC)',
    '- Breve síntese da demanda e do contexto processual',
    '- Transcrição ou resumo da decisão interlocutória agravada',
    '- Consequências da decisão para o agravante',
    '- Mínimo 3-4 parágrafos longos',
    '',
    '## V. DAS RAZÕES PARA REFORMA (art. 1.016, III CPC) — SEÇÃO PRINCIPAL',
    '- Subseções com TÍTULOS DESCRITIVOS EM MAIÚSCULAS',
    '- Cada subseção desenvolve uma tese:',
    '  - Demonstrar o erro da decisão: in judicando ou in procedendo',
    '  - Fundamento legal + jurisprudencial + aplicação ao caso',
    '- Mínimo 3 subseções com 3+ parágrafos longos cada',
    '',
    '## VI. DO EFEITO SUSPENSIVO / DA TUTELA RECURSAL (art. 1.019, I CPC)',
    '### Se necessário efeito suspensivo:',
    '- Probabilidade de provimento do recurso (art. 995, par. único CPC)',
    '- Risco de dano grave ou de difícil reparação',
    '### Se necessária tutela antecipada recursal:',
    '- Probabilidade do direito (art. 300 CPC)',
    '- Perigo de dano ou risco ao resultado útil',
    '',
    '## VII. DOS PEDIDOS',
    '- a) Recebimento e processamento do agravo de instrumento',
    '- b) Concessão de efeito suspensivo / tutela recursal (se aplicável)',
    '- c) Intimação do agravado para contrarrazões (art. 1.019, II CPC)',
    '- d) Provimento do recurso para reformar a decisão agravada',
    '- e) Condenação do agravado nas custas recursais',
  ].join('\n'),

  embargos_declaracao: [
    '# EMBARGOS DE DECLARAÇÃO',
    '> Estrutura conforme CPC/2015, arts. 1.022-1.026',
    '',
    '## I. QUALIFICAÇÃO E ENDEREÇAMENTO',
    '- Embargante: nome e qualificação',
    '- Referência aos autos',
    '- EMBARGOS DE DECLARAÇÃO',
    '- Contra a decisão proferida por (órgão prolator)',
    '- Fundamento: art. 1.022 do CPC',
    '- Por: omissão e/ou contradição e/ou obscuridade',
    '',
    '## II. DA TEMPESTIVIDADE',
    '- Publicação da decisão embargada (data)',
    '- Data de oposição dos embargos',
    '- Prazo de 5 dias úteis observado (art. 1.023, caput, CPC)',
    '',
    '## III. DA DECISÃO EMBARGADA',
    '- Resumo da decisão impugnada (2-3 parágrafos)',
    '- Transcrição dos trechos relevantes onde se identificam os vícios',
    '- Contexto processual necessário',
    '',
    '## IV. DOS VÍCIOS DA DECISÃO',
    '',
    '### DA OMISSÃO (se aplicável — art. 1.022, III CPC)',
    '- Indicar EXATAMENTE o ponto não enfrentado',
    '- Transcrever o trecho da petição onde o ponto foi suscitado',
    '- Demonstrar que a omissão é relevante para o resultado',
    '- Se art. 489, §1º: indicar o inciso violado',
    '- Se art. 927: indicar o precedente não considerado',
    '',
    '### DA CONTRADIÇÃO (se aplicável — art. 1.022, II CPC)',
    '- Transcrever os trechos contraditórios da decisão',
    '- Demonstrar a incompatibilidade lógica',
    '- Indicar qual premissa deve prevalecer',
    '',
    '### DA OBSCURIDADE (se aplicável — art. 1.022, I CPC)',
    '- Transcrever o trecho obscuro/ambíguo',
    '- Apresentar as interpretações possíveis',
    '- Indicar qual esclarecimento é necessário',
    '',
    '### DO PREQUESTIONAMENTO (se aplicável — art. 1.025 CPC)',
    '- Identificar os dispositivos a prequestionar',
    '- Demonstrar que foram suscitados e não enfrentados',
    '- Requerer manifestação expressa',
    '',
    '### DO EFEITO MODIFICATIVO (se aplicável)',
    '- Demonstrar que a correção do vício implica alteração do resultado',
    '- Não é rediscussão: é consequência natural da correção',
    '- Requerer contraditório (art. 1.023, §2º CPC)',
    '',
    '## V. DOS PEDIDOS',
    '- a) Recebimento dos embargos de declaração, por tempestivos',
    '- b) Intimação da parte contrária para manifestar-se (se efeito modificativo)',
    '- c) Acolhimento dos embargos para sanar a omissão / contradição / obscuridade',
    '- d) Prequestionamento dos dispositivos legais (art. 1.025 CPC)',
    '- e) Concessão de efeito suspensivo (art. 1.026, §1º CPC), se aplicável',
    '- Nota: Embargos INTERROMPEM o prazo para outros recursos (art. 1.026, caput)',
  ].join('\n'),
}

